name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: vet
        run: go vet ./...
      
      - name: Test
        run: go test ./...
